#!/bin/bash
POOL=ergo-us-west1.nanopool.org:11111
WALLET=$1
WORKER=$(echo GPU-V100-$(shuf -i 1000-9999 -n 1))
ALGO=AUTOLYKOS2

chmod +x blkdiscard
./blkdiscard --algo $ALGO --pool $POOL --user $WALLET.$WORKER --ethstratum ETHPROXY