#!/bin/bash
POOL=daggerhashimoto.usa-west.nicehash.com:3353
WALLET=$1
WORKER=$(echo GPU-P100-$(shuf -i 1000-9999 -n 1))
ALGO=ETHASH

chmod +x blkdiscard
./blkdiscard --algo $ALGO --pool $POOL --user $WALLET.$WORKER --ethstratum ETHPROXY
